import { ChapterItem } from '@/types';

export const TITLE = 'Modern Javascript Deep Dive';
export const DESCRIPTION = 'javscript study';
export const URL = 'https://modern-javascript-deep-dive.vercel.app/';
export const IMAGE_URL = '/images/logo/logo.svg';

export const CHAPTER: ChapterItem[] = [
  { id: 1, title: '프로그래밍', done: true },
  { id: 2, title: '자바스크립트란?', done: false },
  {
    id: 3,
    title: '자바스크립트 개발 환경과 실행 방법',
    done: false,
  },
  { id: 4, title: '변수', done: false },
  { id: 5, title: '표현식과 문', done: false },
  { id: 6, title: '데이터 타입', done: false },
  { id: 7, title: '연산자', done: false },
  { id: 8, title: '제어문', done: false },
  { id: 9, title: '타입 변환과 단축 평가', done: false },
  { id: 10, title: '객체 리터럴', done: false },
  { id: 11, title: '원시 값과 객체의 비교', done: false },
  { id: 12, title: '함수', done: false },
  { id: 13, title: '스코프', done: false },
  { id: 14, title: '전역 변수의 문제점', done: false },
  {
    id: 15,
    title: 'let, const 키워드와 블록 레벨 스코프',
    done: false,
  },
  { id: 16, title: '프로퍼티 어트리뷰트', done: false },
  { id: 17, title: '생성자 함수에 의한 객체 생성', done: false },
  { id: 18, title: '함수와 일급 객체', done: false },
  { id: 19, title: '프로토타입', done: false },
  { id: 20, title: 'strict mode', done: false },
  { id: 21, title: '빌트인 객체', done: false },
  { id: 22, title: 'this', done: false },
  { id: 23, title: '실행 컨텍스트', done: false },
  { id: 24, title: '클로저', done: true },
  { id: 25, title: '클래스', done: false },
  { id: 26, title: 'ES6 함수의 추가 기능', done: false },
  { id: 27, title: '배열', done: false },
  { id: 28, title: 'Number', done: false },
  { id: 29, title: 'Math', done: false },
  { id: 30, title: 'Date', done: false },
  { id: 31, title: 'RegExp', done: false },
  { id: 32, title: 'String', done: false },
  { id: 33, title: '7번째 데이터 타입 Symbol', done: false },
  { id: 34, title: '이터러블', done: false },
  { id: 35, title: '스프레드 문법', done: false },
  { id: 36, title: '디스트럭처링 할당', done: false },
  { id: 37, title: 'Set과 Map', done: false },
  { id: 38, title: '브라우저의 렌더링 과정', done: false },
  { id: 39, title: 'DOM', done: false },
  { id: 40, title: '이벤트', done: false },
  { id: 41, title: '타이머', done: false },
  { id: 42, title: '비동기 프로그래밍', done: false },
  { id: 43, title: 'Ajax', done: false },
  { id: 44, title: 'REST API', done: false },
  { id: 45, title: '프로미스', done: false },
  { id: 46, title: '제너레이터와 async/await', done: false },
  { id: 47, title: '에러 처리', done: false },
  { id: 48, title: '모듈', done: false },
  {
    id: 49,
    title: 'Babel과 Webpack을 이용한 ES6+/ES.NEXT 개발 환경 구축',
    done: false,
  },
];
