import Chapter01 from '@/components/chapter/Chapter01';
import { ChapterItem } from '@/types';

export const CHAPTER: ChapterItem[] = [
  { id: 1, title: '프로그래밍', component: Chapter01 },
  { id: 2, title: '자바스크립트란?', component: null },
  {
    id: 3,
    title: '자바스크립트 개발 환경과 실행 방법',
    component: null,
  },
  { id: 4, title: '변수', component: null },
  { id: 5, title: '표현식과 문', component: null },
  { id: 6, title: '데이터 타입', component: null },
  { id: 7, title: '연산자', component: null },
  { id: 8, title: '제어문', component: null },
  { id: 9, title: '타입 변환과 단축 평가', component: null },
  { id: 10, title: '객체 리터럴', component: null },
  { id: 11, title: '원시 값과 객체의 비교', component: null },
  { id: 12, title: '함수', component: null },
  { id: 13, title: '스코프', component: null },
  { id: 14, title: '전역 변수의 문제점', component: null },
  {
    id: 15,
    title: 'let, const 키워드와 블록 레벨 스코프',
    component: null,
  },
  { id: 16, title: '프로퍼티 어트리뷰트', component: null },
  { id: 17, title: '생성자 함수에 의한 객체 생성', component: null },
  { id: 18, title: '함수와 일급 객체', component: null },
  { id: 19, title: '프로토타입', component: null },
  { id: 20, title: 'strict mode', component: null },
  { id: 21, title: '빌트인 객체', component: null },
  { id: 22, title: 'this', component: null },
  { id: 23, title: '실행 컨텍스트', component: null },
  { id: 24, title: '클로저', component: null },
  { id: 25, title: '클래스', component: null },
  { id: 26, title: 'ES6 함수의 추가 기능', component: null },
  { id: 27, title: '배열', component: null },
  { id: 28, title: 'Number', component: null },
  { id: 29, title: 'Math', component: null },
  { id: 30, title: 'Date', component: null },
  { id: 31, title: 'RegExp', component: null },
  { id: 32, title: 'String', component: null },
  { id: 33, title: '7번째 데이터 타입 Symbol', component: null },
  { id: 34, title: '이터러블', component: null },
  { id: 35, title: '스프레드 문법', component: null },
  { id: 36, title: '디스트럭처링 할당', component: null },
  { id: 37, title: 'Set과 Map', component: null },
  { id: 38, title: '브라우저의 렌더링 과정', component: null },
  { id: 39, title: 'DOM', component: null },
  { id: 40, title: '이벤트', component: null },
  { id: 41, title: '타이머', component: null },
  { id: 42, title: '비동기 프로그래밍', component: null },
  { id: 43, title: 'Ajax', component: null },
  { id: 44, title: 'REST API', component: null },
  { id: 45, title: '프로미스', component: null },
  { id: 46, title: '제너레이터와 async/await', component: null },
  { id: 47, title: '에러 처리', component: null },
  { id: 48, title: '모듈', component: null },
  {
    id: 49,
    title: 'Babel과 Webpack을 이용한 ES6+/ES.NEXT 개발 환경 구축',
    component: null,
  },
];
